config/routes.rb
Rails.application.routes.draw do
  resources :matches do
    collection do
      get 'launch'
    end
  end
  resources :championnats
  get 'admin/index'

  root 'welcome#index'
  get 'welcome/index'
  get '/show', to:'welcome#show'
  get '/admin', to: 'admin#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/championnat.rb
class Championnat < ApplicationRecord
  has_many :matches

  def self.count_matches
    toReturn = []
    Championnat.all.each do | championnat |
      toReturn.push([championnat.name, championnat.matches.count])
    end
    return toReturn
  end
end

app/models/match.rb
class Match < ApplicationRecord
  belongs_to :championnat


  def self.findInList(list, toFind)
    list.each do |array|
      if array.include?toFind
        return true
      end
    end
    return false
  end

  def self.addScore(list, toFind, score)
    list.each do |array|
      if array.include?toFind
        array[1] += score
      end
    end
    return nil
  end



  def self.sum_goal
    toReturn = []
    Match.all.each do | match |
      unless match.home_score.nil?
        # get goal for home team
        if self.findInList(toReturn, match.home_team)
          self.addScore(toReturn, match.home_team, match.home_score)
        else
          toReturn.push([match.home_team, match.home_score])
        end

        # get goal for Away team
        if self.findInList(toReturn, match.away_team)
          self.addScore(toReturn, match.away_team, match.away_score)
        else
          toReturn.push([match.away_team, match.away_score])
        end
      end
    end
    return toReturn
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_filter :verify_authenticity_token
end

app/controllers/championnats_controller.rb
class ChampionnatsController < ApplicationController
  layout 'admin'

  def index
    @championnats = Championnat.all
    @datas = Championnat.count_matches
  end

  def show
    @championnat = Championnat.find(params[:id])
  end

  def new
    @championnat = Championnat.new
  end

  def create
    @championnat = Championnat.new(championnat_params)
    if @championnat.save
      redirect_to championnats_path
    else
      render 'new'
    end
  end

  def edit
    @championnat = Championnat.find(params[:id])
  end

  def update
    @championnat = Championnat.find(params[:id])
    if @championnat.update(championnat_params)
      redirect_to @championnat
    else
      render 'edit'
    end
  end

  def destroy
    @championnat = Championnat.find(params[:id])
    @championnat.destroy
    redirect_to championnats_path
  end

  private
  def championnat_params
    params.require(:championnat).permit(:name)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  layout 'admin'

  def index
    @matches = Match.all.order(:year, :matchday).paginate(:page => params[:page], :per_page => 380)
    @championnats = Championnat.all
    @datas = Match.sum_goal
  end

  def show
    @match = Match.find(params[:id])
  end

  def new
    @match = Match.new
    @championnats = Championnat.all
  end

  def create
    @match = Match.new(match_params)
    if @match.save
      puts 'match save'
      redirect_to matches_path
    else
      render 'new'
    end
  end

  def edit
    @match = Match.find(params[:id])
  end

  def update
    @match = Match.find(params[:id])
    if @match.update(match_params)
      redirect_to @match
    else
      render 'edit'
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy
    redirect_to matches_path
  end

  def launch
    PredictionJob.perform_async()
    redirect_to matches_path
  end

  private
  def match_params
    params.require(:match).permit(:matchday, :home_team, :home_prevision, :home_prevision, :home_score, :draw_prevision,
                                  :away_team, :away_prevision, :away_score, :championnat_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @current_year = 2016
    @championnat = Championnat.find_by(name: 'Ligue 1')

    unless params[:page]
      params[:page] = @championnat.matches.where(year: @current_year).count / 10
    end

    @matches = Match.where(championnat: @championnat, year: @current_year).order(:matchday).paginate(:page => params[:page], :per_page => 10)
  end

  def show
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/championnats_helper.rb
module ChampionnatsHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/_nav.html.erb
<nav>
  <div class="nav-wrapper">
    <a href="#" class="brand-logo"></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><a href="<%= welcome_index_path %>">Accueil</a></li>
      <li><a href="<%= championnats_path %>">Gestion des championnats</a></li>
      <li><a href="<%= matches_path %>">Gestion des matchs</a></li>
    </ul>
  </div>
</nav>

app/views/application/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <h6>Clément Roussy</h6>
    </div>
  </div>
</footer>

app/views/application/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li>
        <%= link_to "Gestion back office".html_safe, admin_path %>
      </li>
    </ul>
  </div>
</nav>

app/views/championnats/edit.html.erb
<%= simple_form_for @championnat do |f| %>
<%= f.input :name %>
<%= f.button :submit, 'Valider' %>
<% end %>

app/views/championnats/index.html.erb
<h2>Liste des championnats</h2>
<div class="row">
  <%= link_to 'nouveau championnat', new_championnat_path, class: 'btn' %>
  <% @championnats.each do |championnat| %>
    <div class="col.s12.m6">
      <div class="card">
        <div class="card-content">
          <span class='card-title'> <%= championnat.name %></span>
          <div class="card-action">
            <%= link_to "Edit", edit_championnat_path(championnat.id), class: 'fa fa-pencil' %>
            <%= link_to "<span class='fa fa-close'>Delete</span>".html_safe,
                        championnat_path(championnat.id),
                        method: :delete,
                        data: { confirm: 'Confirmer la suppression ?' }%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<h3>Nombre de match par championnat</h3>
<%= pie_chart(@datas) %>

app/views/championnats/new.html.erb
<%= simple_form_for @championnat do |f| %>
<%= f.input :name %>
<%= f.button :submit, 'Valider' %>
<% end %>

app/views/championnats/show.html.erb
<div class="row">
    <div class="col.s12.m6">
      <div class="card">
        <div class="card-content">
          <span class='card-title'> <%= @championnat.name %></span>
          <div class="card-action">
            <%= link_to "<span class='fa fa-pencil'>Edit</span>".html_safe, edit_championnat_path( @championnat.id )%>
            <%= link_to "<span class='fa fa-close'>Delete</span>".html_safe,
                        championnat_path( @championnat.id ),
                        method: :delete,
                        data: { confirm: 'Confirmer la suppression ?' }%>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <%= render partial:'admin/nav' %>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InitiationRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag "https://www.google.com/jsapi" %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'header' %>
    <main>
      <%= yield %>
    </main>
    <%= render 'footer' %>
  </body>
</html>

app/views/matches/edit.html.erb
<h2>Enregistrement d'un match</h2>
<%= simple_form_for @match do |f| %>
  <%= f.input  :matchday %>
  <%= f.association  :championnat %>
  <%= f.input  :home_team %>
  <%= f.input  :home_prevision %>
  <%= f.input  :home_score %>
  <%= f.input  :draw_prevision %>
  <%= f.input  :away_team %>
  <%= f.input  :away_prevision %>
  <%= f.input  :away_score %>
<%= f.button :submit, 'Valider' %>
<% end %>

app/views/matches/index.html.erb
<h2>Liste des matchs</h2>
<div class="row">
  <%= link_to 'nouveau match', new_match_path, class: 'btn' %>
  <%= link_to "Lancer l'algorithme", {controler: 'matches', action: 'launch'}, class: 'btn' %>
    <div class="col.s12.m6">
      <div class="row">
        <div class="center-align">
          <%= will_paginate @matches %>
        </div>
      </div>
      <table class="striped">
        <thead>
          <tr>
            <th data-field='championnat'>Championnat</th>
            <th data-field='annee'>Année</th>
            <th data-field='matchday'>Match day</th>
            <th data-field='home_team'>Home team</th>
            <th data-field='home_prevision'>Home prevision</th>
            <th data-field='draw_prevision'>Draw prevision</th>
            <th data-field='score'>Score</th>
            <th data-field='away_prevision'>away prevision</th>
            <th data-field='away_team'>Away team</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @matches.each do |match| %>
            <tr>
              <td><%= match.championnat.name %></td>
              <td><%= match.year %></td>
              <td><%= match.matchday %></td>
              <td><%= match.home_team %></td>
              <td><%= !match.home_prevision.nil? ? (match.home_prevision.round(4) * 100).to_s + ' %' : '' %></td>
              <td><%= !match.draw_prevision.nil? ? (match.draw_prevision.round(4) * 100).to_s + ' %' : '' %></td>
              <td><%= match.home_score %> - <%= match.away_score %></td>
              <td><%= !match.away_prevision.nil? ? (match.away_prevision.round(4) * 100).to_s + ' %' : '' %></td>
              <td><%= match.away_team %></td>
              <td><%= link_to "Editer", edit_match_path(match.id) %></td>
              <td>
                <%=  link_to "<span class='fa fa-close'>Supprimer</span>".html_safe,
                        match_path(match.id),
                        method: :delete,
                        data: { confirm: 'Confirmer la suppression ?' }%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div class="row">
        <div class="center-align">
          <%= will_paginate @matches %>
        </div>
      </div>
    </div>
</div>
<h3>Nombre de buts par équipe</h3>
<%= column_chart(@datas) %>

app/views/matches/new.html.erb
<h2>Enregistrement d'un match</h2>
<%= simple_form_for @match do |f| %>
  <%= f.input  :matchday %>
  <%= f.association  :championnat %>
  <%= f.input  :home_team %>
  <%= f.input  :home_prevision %>
  <%= f.input  :home_score %>
  <%= f.input  :draw_prevision %>
  <%= f.input  :away_team %>
  <%= f.input  :away_prevision %>
  <%= f.input  :away_score %>
<%= f.button :submit, 'Valider' %>
<% end %>

app/views/matches/show.html.erb
<div class="row">
    <div class="col.s12.m6">
      <div class="card">
        <div class="card-content">
          <span class='card-title'> <%= @match.home_team %> - <%=	@match.away_team %></span>
          <hr>
          <div class="card-action">
            <%= link_to "<span class='fa fa-pencil'>Editer</span>".html_safe, edit_match_path( @match.id )%>
            <%= link_to "<span class='fa fa-close'>Supprimer</span>".html_safe,
                        match_path( @match.id ),
                        method: :delete,
                        data: { confirm: 'Confirmer la suppression ?' }%>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <h2 class="center-align"><%= @championnat.name %> - <%= @current_year %></h2>
      <div class="center-align">
        <table class="striped">
          <thead>
            <tr>
              <th>Home team</th>
              <th>Home win provision</th>
              <th>Draw win provision</th>
              <th>Score</th>
              <th>Away win provision</th>
              <th>Away team</th>
            </tr>
          </thead>
          <tbody>
            <%- @matches.each do |match| %>
              <tr>
                <td><%= match.home_team %></td>
                <td><%= match.home_score.nil? ? (match.home_prevision.round(4) * 100).to_s + ' %' : '' %></td>
                <td><%= match.draw_prevision.nil? ? '' : (match.draw_prevision.round(4) * 100).to_s + ' %'%></td>
                <td>
                  <span class="<%= match.home_score.nil? ? '' : match.home_score > match.away_score ? 'active' : '' %>">
                  <%= match.home_score.nil? ? '' :  match.home_score %></span> - <span class="<%= match.away_score.nil? ? '' : match.away_score > match.home_score ? 'active': '' %>">
                  <%= match.away_score.nil? ? '' : match.away_score %> </span>
                </td>
                <td><%= match.away_score.nil? ? (match.away_prevision.round(4) * 100).to_s + ' %' : '' %></td>
                <td><%= match.away_team %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <br/>
    <div class="row">
      <div class="center-align">
        <%= will_paginate @matches %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/show.html.erb
<h1>Welcome#show</h1>
<p>Find me in app/views/welcome/index.html.erb</p>